### PR TITLE
Fix infinite looping issue

### LINKED ISSUE #15: A CTRL+D make bshell infinite looping
A CTRL+D should exit bshell, not make it infinite looping

### PR DESCRIPTION
**Pull request by bihanviranga**
Fixes #15

### CODE REVIEW

File: src/main.c [hunk 1]
```diff
@@ -54,6 +54,11 @@ char *bshell_read_line() {
     // Read a character
     c = getchar();
 
+    // Ctrl+D makes the shell loop infinitely.
+    // A quick printf reveals that ctrl+d makes c equal to -1.
+    if (c == -1) {
```
Comment (buffet) [inline src/main.c]: It's not guaranteed to return -1, it returns EOF (defined in stdio.h), you should check for that instead (and remove the check a few lines down).

**Review by buffet — CHANGES_REQUESTED** [review]

**Comment by bihanviranga** [comment]
@buffet I finally understood what you meant. I have been thinking about EOF all wrong.
Hope I fixed it right. Thanks for the guidance. <3
